server:
  contextPath: /api
  port: 8008
 
spring:
  data:
    mongodb:
      uri: mongodb://myretail_user:password123@127.0.0.1:27017/myretail
      
product.service.url: http://localhost:9008/external-api/products/{id}  